### ISSUE TITLE
IMPORTANT: Please fix testing - add node.js 18.x and 20.x tests

### ISSUE THREAD

**Issue by mcm1957** [kBrausew/ioBroker.wiegand-tcpip#16]
Github based testing MUST be done as following

- if engines clause at package.json states >= 18 node.js 18 tests must be active and pass
- node.js 20 tests must always be active and pass
- node.js 22 tests must be active and pass unless there is some incompatibility and an issue to fix this exists.

**As engines clause states >= 18 at package.json please adapter test matrix to test at 18.x, 20.x and 22.x**

In addition your tests are failing due to an invalid package-lock.json file.
Please fix (i.e. by executing npm install within working directory to rebuild this file)

**Comment by mcm1957** [comment]
Shpuld be fixed by PR https://github.com/kBrausew/ioBroker.wiegand-tcpip/pull/18

**Comment by kBrausew** [comment]
closed with PR#18 merge
