### ISSUE TITLE
*URGENT* - please fix io-package.json

### ISSUE THREAD

**Issue by mcm1957** [kBrausew/ioBroker.wiegand-tcpip#7]
io-package.json is syntactically invalid at end of nes section.
PR https://github.com/kBrausew/ioBroker.wiegand-tcpip/pull/6 should fix it. Please check and merge.

As the corrupt file blocks repository updates your adapetr has een (temporary) removed from repositories. Please drop a not and mention me (@mcm1957) to readd the adapter as soon as the file is fixed

**Comment by kBrausew** [comment]
Pull request done... closed issue

**Comment by mcm1957** [comment]
THANKS
